name: byDennyysEssentials
version: '1.0'
main: de.bydennyy.byDennyysEssentials.Main
bootstrapper: de.bydennyy.byDennyysEssentials.Bootstrapper
api-version: '1.21'

dependencies:
  server:
    LuckPerms:
      load: BEFORE
      required: false
    WorldEdit:
      load: BEFORE
      required: false

permissions:
  dennyy.essentials.alias.show:
    description: allows the player to use all alias commands
    default: true
  dennyy.essentials.command.alias:
    description: allows the player to use the /alias command
    default: false
  dennyy.essentials.command.lightning:
    description: allows player to use the lightning command
    default: false
  dennyy.essentials.command.ec:
    description: allows player to use the lightning command
    default: false
    children:
      dennyy.essentials.command.ec.self: true
  dennyy.essentials.command.ec.self:
    description: allows player to use the lightning command
    default: false
  dennyy.essentials.command.ec.edit:
    description: allows player to use the lightning command
    default: false

